// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdJ8fIGC_TCpR1jPu56GrqvckcHsjIh8',
    appId: '1:970161125324:web:87588009cffbc06b8c8f69',
    messagingSenderId: '970161125324',
    projectId: 'fudebako-dev',
    authDomain: 'fudebako-dev.firebaseapp.com',
    storageBucket: 'fudebako-dev.firebasestorage.app',
    measurementId: 'G-TJC8D9B7T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGa6IY3wN600mBiytal8ga9OOQ7zeCUKU',
    appId: '1:970161125324:android:0567769dc9bc73c98c8f69',
    messagingSenderId: '970161125324',
    projectId: 'fudebako-dev',
    storageBucket: 'fudebako-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv3HfcXIM-sSNcl6RZMhOMuUDzL63ICts',
    appId: '1:970161125324:ios:1b39c36c716c3f8b8c8f69',
    messagingSenderId: '970161125324',
    projectId: 'fudebako-dev',
    storageBucket: 'fudebako-dev.firebasestorage.app',
    iosClientId: '970161125324-ujk8musude4uukc5ifvpt06dee4srl5s.apps.googleusercontent.com',
    iosBundleId: 'com.mattrohde.gakuji',
  );
}
